- name: 28 playbook
  hosts: all
  tasks:
  - name: lineinfile
    lineinfile:
      dest: /tmp/test.conf
      line:  'line number \1'
      #line: 'number = 3'
      insertbefore: "^(number [0-9])"
      state: present